Issue #23
datopian/frontend-showcase-js pull request #68
Opened 2017-01-23 15:04 UTC by anuveyatsu

* implemented vega-lite as a node module
* refactored DataPackageViewContainer to support vega-lite graph type
* refactored vegalite component to render single series chart
* refactored vegalite component to render multiple charts with single series

2017-01-23 16:10 UTC, Fak3 requested changes

2017-01-23 16:10 UTC, Fak3 commented on src/containers/DataPackageViewContainer.js
>    generateSpec(view) {
Probably it is worth renaming to smth like generatePlotlySpec() now

2017-01-23 16:10 UTC, Fak3 commented on src/containers/DataPackageViewContainer.js
>      //render PlotlyChart component and pass data, layout, and index
This comment is incorrect now

2017-01-23 16:13 UTC, Fak3 commented on src/containers/DataPackageViewContainer.js
>      //render PlotlyChart component and pass data, layout, and index
Can you please also fix the description of DataPackageViewContainer in the topmost comment?

2017-01-23 16:46 UTC, Fak3 requested changes
Can you please fix  test - "should generate spec for Plotly" it should use new method name.

And please launch tests to check that all tests pass

2017-01-23 16:56 UTC, anuveyatsu commented
@Fak3 tests for containers are passimg. However, I'm working on fixing tests for chart and table rendering - we have been discussing that with @subhankarb. We will handle it as we replace Jest with Mocha.

2017-01-23 16:57 UTC, Fak3 approved these changes
LGTM

2017-01-24 04:26 UTC, merged

2017-01-24 04:26 UTC, subhankarb reviewed
LGTM